### ISSUE TITLE
Add thumbnail images for each script

### ISSUE THREAD

**Issue by ohbendy** [ohbendy/Scripts-of-SEAsia#1]
As some of these scripts are extremely obscure outside their communities, it'll be helpful to be able to identify what scripts we're talking about.

**Comment by ohbendy** [comment]
Do you mean to create vector graphics for every script? That'll need a lot of research and drawing. I was just thinking a small .png for each

**Comment by ohbendy** [comment]
To discuss:

 - [ ] Can we add a beta copy of the site so we can play with features without making them fully live?
 - [ ] Adding images: a short line of real text, or ကခဂဃငစဆဇဈည? Could it be clickable to get a bigger (uncropped) image?

**Comment by sovichet** [comment]
>  Can we add a beta copy of the site so we can play with features without making them fully live?

There are a few ways we can do it.

## 1. Checkout another branch within the same repo (no live page)

First, we'll need to checkout a new branch and start working on that branch. Add or remove anything we want, but when pushing the commits, it won't be live. And we need to run `bundle exec jekyll serve` to test the changes on local machines.

Later, when everything is good, we can set up a pull request and then merge it to the `main` branch which will be compiled into the live page.

## 2. Fork this project, and get another page domain (live page)

If you want to test the changes and make it available for other people, we'll need to fork this repo to something like "Scripts-of-SEAsia-Beta".

Since it's impossible to fork the GitHub repo under the same username, we'll need to fork this project under my account. And I'll add you as a collaborator and we'll get the live site at "https://sovichet.github.io/Scripts-of-SEAsia-Beta" instead. Then we can set up a pull request and merge later.

---

I'd recommend the first option, so we can have the record of changes and easily manage.

**Comment by ohbendy** [comment]
I think we'll need the beta site to be accessible to other people, so we can check we've got the right images for each row. What a shame we can't fork it directly in the same place. Let me collect a few thumbnail images so we can see how difficult it's going to be to get them looking neat in the table, then we can chat about the best way, maybe a beta site isn't the best way :)

**Comment by sovichet** [comment]
Maybe we can go this way: duplicate the markdown files and change them within this branch. I've just created the `index_dev.md` and `_source/writingsystems_dev.markdown` files. They can be accessed via: https://ohbendy.github.io/Scripts-of-SEAsia/index_dev.

**Comment by ohbendy** [comment]
Ok I've added most images now, we'll consider how to make them interactive after we've switched from .md to .js

**Comment by ohbendy** [comment]
I'll close this issue for now. If we're going to have interactive images and/or more popup info, we'll need to think about what's possible and can open new issues for that
